[[skills]]
name = "grill-me"
repository = "mattpocock/skills"
path = "skills/productivity/grilling"
commit = "bfdaef8e989a5c81160e74bc5043bd434da49cac"

[[skills]]
name = "domain-modeling"
repository = "mattpocock/skills"
path = "skills/engineering/domain-modeling"
commit = "54bc6b604075c18293d38e9e294a2c96f365f104"
