[[skills]]
name = "grill-me"
repository = "mattpocock/skills"
path = "skills/productivity/grilling"
commit = "85f83d3fde1d3a90d5c9a657f6998c79a6c37308"

[[skills]]
name = "domain-modeling"
repository = "mattpocock/skills"
path = "skills/engineering/domain-modeling"
commit = "d80fa0f4ebe0c5714af0adf8670336065233ecc6"
